[project]
name = "pantrydb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.9.4",
    "sqlalchemy",
    "alembic>=1.16.2",
    "psycopg2>=2.9.10",
]
